;;; build-resources.lisp
;;; Генерирует src/resources.lisp из файлов в resources/

(defun read-file-to-bytes (path)
  (with-open-file (stream path :element-type '(unsigned-byte 8))
    (let ((data (make-array (file-length stream) :element-type '(unsigned-byte 8))))
      (read-sequence data stream)
      data)))

(defun read-file-to-string (path)
  (with-open-file (stream path)
    (let ((data (make-string (file-length stream))))
      (read-sequence data stream)
      data)))

(defun usb8-array-to-base64-string (bytes)
  (let ((result (make-string (* (ceiling (length bytes) 3) 4)))
        (chars "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/")
        (idx 0))
    (loop for i from 0 below (length bytes) by 3
          for b0 = (aref bytes i)
          for b1 = (when (< (1+ i) (length bytes)) (aref bytes (1+ i)))
          for b2 = (when (< (+ 2 i) (length bytes)) (aref bytes (+ 2 i)))
          do (setf (aref result idx) (aref chars (ash b0 -2)))
             (setf (aref result (1+ idx))
                   (aref chars (logior (ash (logand b0 3) 4)
                                       (if b1 (ash b1 -4) 0))))
             (setf (aref result (+ idx 2))
                   (if b1 (aref chars (logior (ash (logand b1 15) 2)
                                              (if b2 (ash b2 -6) 0)))
                       #\=))
             (setf (aref result (+ idx 3))
                   (if b2 (aref chars (logand b2 63)) #\=))
             (incf idx 4))
    result))

(defun build-resources ()
  (let* ((base (asdf:system-source-directory :lisper))
         (resources-dir (merge-pathnames #P"resources/" base))
         (output (merge-pathnames #P"src/resources.lisp" base))
         (logo-svg (read-file-to-string (merge-pathnames #P"logo.svg" resources-dir)))
         (favicon-bytes (read-file-to-bytes (merge-pathnames #P"favicon.svg" resources-dir)))
         (favicon-b64 (usb8-array-to-base64-string favicon-bytes)))
    (with-open-file (stream output :direction :output :if-exists :supersede)
      (format stream "(in-package :lisper)~%~%")
      (format stream "(defparameter *logo-svg*~%  ~S)~%~%" logo-svg)
      (format stream "(defparameter *favicon-data-uri*~%  (concatenate 'string~%               \"data:image/svg+xml;base64,\"~%               ~S))~%" favicon-b64))
    (format t "Generated ~a~%" output)))

(build-resources)
