;;; build-resources.lisp
;;; Генерирует src/resources.lisp из файлов в resources/

(defun read-file-to-bytes (path)
  (with-open-file (stream path :element-type '(unsigned-byte 8))
    (let ((data (make-array (file-length stream) :element-type '(unsigned-byte 8))))
      (read-sequence data stream)
      data)))

(defun read-file-to-string (path)
  (with-open-file (stream path :external-format :utf-8)
    (let* ((size (file-length stream))
           (data (make-string size))
           (pos (read-sequence data stream)))
      (subseq data 0 pos))))

(defun usb8-array-to-base64-string (bytes)
  (let ((result (make-string (* (ceiling (length bytes) 3) 4)))
        (chars "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/")
        (idx 0))
    (loop for i from 0 below (length bytes) by 3
          for b0 = (aref bytes i)
          for b1 = (when (< (1+ i) (length bytes)) (aref bytes (1+ i)))
          for b2 = (when (< (+ 2 i) (length bytes)) (aref bytes (+ 2 i)))
          do (setf (aref result idx) (aref chars (ash b0 -2)))
             (setf (aref result (1+ idx))
                   (aref chars (logior (ash (logand b0 3) 4)
                                       (if b1 (ash b1 -4) 0))))
             (setf (aref result (+ idx 2))
                   (if b1 (aref chars (logior (ash (logand b1 15) 2)
                                              (if b2 (ash b2 -6) 0)))
                       #\=))
             (setf (aref result (+ idx 3))
                   (if b2 (aref chars (logand b2 63)) #\=))
             (incf idx 4))
    result))

(defun build-resources ()
  (let* ((base (asdf:system-source-directory :lisper))
         (resources-dir (merge-pathnames #P"resources/" base))
         (output (merge-pathnames #P"src/resources.lisp" base))
         (logo-svg (read-file-to-string (merge-pathnames #P"logo.svg" resources-dir)))
         (favicon-bytes (read-file-to-bytes (merge-pathnames #P"favicon.svg" resources-dir)))
          (favicon-b64 (usb8-array-to-base64-string favicon-bytes))
          (jscl-js (read-file-to-string (merge-pathnames #P"jscl.js" resources-dir))))
    (with-open-file (stream output :direction :output :if-exists :supersede)
      (format stream "(in-package :lisper)~%~%")
      (format stream "(defparameter *logo-svg*~%  ~S)~%~%" logo-svg)
      (format stream "(defparameter *favicon-data-uri*~%  (concatenate 'string~%               \"data:image/svg+xml;base64,\"~%               ~S))~%" favicon-b64)
      (format stream "(defparameter *jscl-js*~%  ~S)~%" jscl-js))
    (format t "Generated ~a~%" output)))

;;; ============================================================
;;; Game sources — эмбеддинг CL-кодов игр из jscl-games/
;;; ============================================================

(defun build-game-sources ()
  (let* ((base (asdf:system-source-directory :lisper))
         (games-dir (merge-pathnames #P"jscl-games/" base))
         (output (merge-pathnames #P"src/game-sources.lisp" base))
         (games '()))
    ;; Собрать .lisp и .js файлы из jscl-games/
    (when (probe-file games-dir)
      (dolist (f (directory (merge-pathnames #P"*.lisp" games-dir)))
        (let ((name (pathname-name f))
              (source (read-file-to-string f)))
          (push (list name "cl" source) games)))
      (dolist (f (directory (merge-pathnames #P"*.js" games-dir)))
        (let ((name (pathname-name f))
              (source (read-file-to-string f)))
          (push (list name "js" source) games))))
    (setf games (nreverse games))
    ;; Записать game-sources.lisp
    (with-open-file (stream output :direction :output :if-exists :supersede)
      (format stream "(in-package :lisper)~%~%")
      (format stream ";;; Автоматически сгенерировано build-resources.lisp~%")
      (format stream ";;; Источники: jscl-games/*.{lisp,js}~%~%")
      (format stream "(defparameter *game-sources* '~%  (~%")
      (dolist (g games)
        (format stream "    (~s ~s ~s)~%" (first g) (second g) (third g)))
      (format stream "    ))~%~%")
      (format stream "(defun get-game-source (name)~%")
      (format stream "  \"Возвращает (lang . source) игры по имени.\"~%")
      (format stream "  (let ((g (assoc name *game-sources* :test #'string=)))~%")
      (format stream "    (when g (cons (second g) (third g)))))~%"))
    (format t "Generated ~a (~a games)~%" output (length games))))

;;; ============================================================
;;; Tool sources — эмбеддинг CL-кодов утилит из jscl-tools/
;;; ============================================================

(defun build-tool-sources ()
  (let* ((base (asdf:system-source-directory :lisper))
         (tools-dir (merge-pathnames #P"jscl-tools/" base))
         (output (merge-pathnames #P"src/tool-sources.lisp" base))
         (tools '()))
    (when (probe-file tools-dir)
      (dolist (f (directory (merge-pathnames #P"*.lisp" tools-dir)))
        (let ((name (pathname-name f))
              (source (read-file-to-string f)))
          (push (list name "cl" source) tools))))
    (setf tools (nreverse tools))
    (with-open-file (stream output :direction :output :if-exists :supersede)
      (format stream "(in-package :lisper)~%~%")
      (format stream ";;; Автоматически сгенерировано build-resources.lisp~%")
      (format stream ";;; Источники: jscl-tools/*.lisp~%~%")
      (format stream "(defparameter *tool-sources* '~%  (~%")
      (dolist (t- tools)
        (format stream "    (~s ~s ~s)~%" (first t-) (second t-) (third t-)))
      (format stream "    ))~%~%")
      (format stream "(defun get-tool-source (name)~%")
      (format stream "  \"Возвращает (lang . source) утилиты по имени.\"~%")
      (format stream "  (let ((g (assoc name *tool-sources* :test #'string=)))~%")
      (format stream "    (when g (cons (second g) (third g)))))~%"))
    (format t "Generated ~a (~a tools)~%" output (length tools))))

;;; ============================================================
;;; Migrations — эмбеддинг SQL-файлов из migrations/
;;; ============================================================

(defun parse-migration-version (filename)
  "Извлекает version и direction из имени файла типа 0001-initial-schema.up.sql"
  (let* ((name (pathname-name filename))
         (dir-position (search ".up" name))
         (direction (if dir-position :up :down))
         (base-name (if dir-position
                        (subseq name 0 dir-position)
                        (subseq name 0 (- (length name) (length ".down"))))))
    (let ((dash-pos (position #\- base-name)))
      (when dash-pos
        (values (parse-integer (subseq base-name 0 dash-pos))
                direction)))))

(defun build-migrations ()
  (let* ((base (asdf:system-source-directory :lisper))
         (migrations-dir (merge-pathnames #P"migrations/" base))
         (output (merge-pathnames #P"src/migrations.lisp" base))
         (migrations (make-hash-table)))
    (when (probe-file migrations-dir)
      (dolist (f (directory (merge-pathnames #P"*.sql" migrations-dir)))
        (multiple-value-bind (version direction) (parse-migration-version (file-namestring f))
          (when (and version direction)
            (let ((sql (read-file-to-string f)))
              (unless (gethash version migrations)
                (setf (gethash version migrations) (make-hash-table)))
              (setf (gethash direction (gethash version migrations)) sql))))))
    ;; Собрать отсортированный список версий
    (let ((versions (sort (loop for k being the hash-keys of migrations collect k) #'<)))
      (with-open-file (stream output :direction :output :if-exists :supersede)
        (format stream "(in-package :lisper)~%~%")
        (format stream ";;; Embedded migration SQL files~%")
        (format stream ";;; Generated from migrations/*.sql — do not edit manually~%~%")
        (format stream "(defvar *migrations*~%  '(")
        (dolist (v versions)
          (let ((dirs (gethash v migrations)))
            (format stream "~%    (~A . ((:up . ~S)~%" v (gethash :up dirs))
            (format stream "          (:down . ~S)))" (gethash :down dirs))))
        (format stream "))~%~%")
        (format stream "(defun get-available-migrations ()~%")
        (format stream "  \"Return sorted list of (version name) from embedded migrations.\"~%")
        (format stream "  (sort (mapcar (lambda (entry)~%")
        (format stream "                  (list (car entry)~%")
        (format stream "                        (format nil \"migration-~~A\" (car entry))))~%")
        (format stream "                *migrations*)~%")
        (format stream "        #'< :key #'first))~%~%")
        (format stream "(defun get-migration-sql (version direction)~%")
        (format stream "  \"Get SQL for a migration version and direction (:up or :down).\"~%")
        (format stream "  (let ((entry (assoc version *migrations*)))~%")
        (format stream "    (when entry~%")
        (format stream "      (cdr (assoc direction (cdr entry))))))~%"))
      (format t "Generated ~a (~a migrations)~%" output (length versions)))))

(build-resources)
(build-game-sources)
(build-tool-sources)
(build-migrations)
(quit)
